services:
  server:
    build: ./backend
  web:
    build: ./frontend
    environment:
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host
  caddy:
    build: ./caddy
    ports:
      - "8080:80"
    environment:
      API_UPSTREAM: server:8080
      WEB_UPSTREAM: web:3001
    depends_on:
      - web
      - server
