spring.application.name=2idiotz
server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=${POSTGRES_USER:app}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.connectTimeout=3
spring.datasource.hikari.data-source-properties.socketTimeout=5
server.shutdown=graceful
