spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD}
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    open-in-view: false
    properties:
      hibernate.mapping.default_list_semantics: LIST
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration,classpath:seed
    connect-retries: 30
  mvc:
    static-path-pattern: /stops-images/**
  web:
    resources:
      static-locations: classpath:/seed/stopsImages/
  application:
    name: 2idiotz

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  shutdown: graceful

springdoc:
  api-docs:
    enabled: false
